# Generated by Django 5.2 on 2025-04-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='food_name',
            field=models.CharField(default='Food Item', max_length=255),
        ),
    ]
