# Generated by Django 5.2 on 2025-04-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_tracker', '0002_foodentry_food_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='fiber',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Snack', 'Snack'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='sugar',
            field=models.FloatField(default=0),
        ),
    ]
