# Generated by Django 4.2.8 on 2025-04-07 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_from_fitbit', models.IntegerField()),
                ('activity_date', models.DateField()),
                ('total_steps', models.IntegerField()),
                ('total_distance', models.FloatField()),
                ('very_active_minutes', models.IntegerField()),
                ('lightly_active_minutes', models.IntegerField()),
                ('calories', models.IntegerField()),
            ],
            options={
                'unique_together': {('id_from_fitbit', 'activity_date')},
            },
        ),
    ]
